version: '3'

services:
  mock-api:
    image: "wiremock/wiremock:3.5.2"
    ports:
      - "8000:8000"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
    entrypoint: ["/docker-entrypoint.sh", "--port=8000"]
  database:
    image: postgres:15
    environment:
      POSTGRES_DB: deliveries
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
  application:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    depends_on:
      - mock-api
      - database
